base:
  value: "R"
  bed: "/groups/umcg-fg/tmp01/projects/pgx-passport/tools/PGx-passport-pilot/data/cyp2d6/cyp2d6.bed"
batch correction:
  pca_scaling: true
  pca_n_components: 100
  pca_over_samples: false
  regression_fit_intercept: true
naive clustering:
  - [22, 42525043, 42525045]
variant selection:
  "/groups/umcg-fg/tmp01/projects/pgx-passport/tools/PGx-passport-pilot/data/cyp2d6/configuration_bed_files/variants_to_genotype.bed"
cnv calling:
  clustering_max_iter: 1000
  genotype_labels: [-2, -1, 0, 1]
  k_nearest_neighbours: 0
